# .github/workflows/update-commit-sha.yml
name: Update commit_sha.txt

on:
  workflow_call:

jobs:
  update-commit-sha:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CLASSIC_WRITE }}
        
      - name: Append commit SHA to file
        run: |
          echo "${GITHUB_SHA}" >> commit_sha.txt
          echo "${{ secrets.WRITE_TEST_REPO }}"
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        env:
          GH_TOKEN: ${{ secrets.READ_TEST_REPO }}
          
      - name: Commit changes
        run: |
          git add commit_sha.txt
          git commit -m "Add commit SHA ${GITHUB_SHA}"
          git remote set-url origin https://x-access-token:${{ secrets.READ_TEST_REPO }}@github.com/${{ github.repository }}.git
          git push origin HEAD:${{ github.ref }}
        env:
          GH_TOKEN: ${{ secrets.READ_TEST_REPO }}
