name: Update commit_sha.txt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  update-commit-sha:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Append commit SHA to file
        run: |
          echo "${GITHUB_SHA}" >> commit_sha.txt

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit changes
        run: |
          git add commit_sha.txt
          git commit -m "Add commit SHA ${GITHUB_SHA}"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
